version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    networks:
      - lamp-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: alvarado123
      MYSQL_DATABASE: llanura_bd
      MYSQL_USER: alvarado
      MYSQL_PASSWORD: alvarado123
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: alvarado123
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lamp-network
    
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./laravel:/app
    networks:
      - lamp-network
    entrypoint: ["tail", "-f", "/dev/null"]

  node:
    image: node:18
    container_name: node
    ports:
      - "5173:5173"
    volumes:
      - ./laravel:/app
    working_dir: /app
    networks:
      - lamp-network
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  db-data:

networks:
  lamp-network:
